In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [54]:
df=pd.read_csv('Travel.csv')

In [55]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [56]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [57]:
cols=df.columns
cols=np.array(cols)
cols

array(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender',
       'NumberOfPersonVisiting', 'NumberOfFollowups', 'ProductPitched',
       'PreferredPropertyStar', 'MaritalStatus', 'NumberOfTrips',
       'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype=object)

In [58]:
cat_cols=df.select_dtypes(include='object').columns
cat_cols

Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')

In [59]:
for col in cat_cols:
    print(df[col].value_counts())

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64
Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64
Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64
ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64
MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64
Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [60]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [61]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [62]:
df['Gender']=df['Gender'].replace('Fe Male','Female')
df['MaritalStatus']=df['MaritalStatus'].replace('Single','Unmarried')

In [63]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [64]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [65]:
df.dtypes

CustomerID                    int64
ProdTaken                     int64
Age                         float64
TypeofContact                object
CityTier                      int64
DurationOfPitch             float64
Occupation                   object
Gender                       object
NumberOfPersonVisiting        int64
NumberOfFollowups           float64
ProductPitched               object
PreferredPropertyStar       float64
MaritalStatus                object
NumberOfTrips               float64
Passport                      int64
PitchSatisfactionScore        int64
OwnCar                        int64
NumberOfChildrenVisiting    float64
Designation                  object
MonthlyIncome               float64
dtype: object

In [66]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [67]:
#8 cols contain null values impute them if categorical then with mode else median of the col
null_cols=df.columns[df.isnull().any()].to_list()
null_cols

['Age',
 'TypeofContact',
 'DurationOfPitch',
 'NumberOfFollowups',
 'PreferredPropertyStar',
 'NumberOfTrips',
 'NumberOfChildrenVisiting',
 'MonthlyIncome']

In [68]:
for col in null_cols:
    if(df[col].dtype=='float64' or df[col].dtype=='int64'):
        df[col]=df[col].fillna(df[col].median())
    if(df[col].dtype=='object'):
        df[col]=df[col].fillna(df[col].mode()[0])

In [69]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [70]:
#drop customer id
df=df.drop('CustomerID',axis=1)

In [71]:
df.columns

Index(['ProdTaken', 'Age', 'TypeofContact', 'CityTier', 'DurationOfPitch',
       'Occupation', 'Gender', 'NumberOfPersonVisiting', 'NumberOfFollowups',
       'ProductPitched', 'PreferredPropertyStar', 'MaritalStatus',
       'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [72]:
df['TotalVisiting']=df['NumberOfPersonVisiting']+df['NumberOfChildrenVisiting']
df=df.drop(['NumberOfPersonVisiting','NumberOfChildrenVisiting'],axis=1)

In [73]:
#total features
num_features=[feature for feature in df.columns if df[feature].dtype!='O']
cat_features=[feature for feature in df.columns if df[feature].dtype=='O']
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
continuos_features=[feature for feature in num_features if len(df[feature].unique())>25]

In [74]:
print(f'num_features:{num_features}')
print(f'cat_features:{cat_features}')
print(f'discrete_features:{discrete_features}')
print(f'continuos_features:{continuos_features}')

num_features:['ProdTaken', 'Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting']
cat_features:['TypeofContact', 'Occupation', 'Gender', 'ProductPitched', 'MaritalStatus', 'Designation']
discrete_features:['ProdTaken', 'CityTier', 'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar', 'TotalVisiting']
continuos_features:['Age', 'DurationOfPitch', 'MonthlyIncome']

In [75]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

convert into standard scaler and categorical into numerical

In [76]:
X=df.drop('ProdTaken',axis=1)
y=df['ProdTaken']

In [77]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [81]:
cat_features=X.select_dtypes(include='object').columns
num_features=X.select_dtypes(exclude='object').columns



from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

oh_transformer=OneHotEncoder(drop='first')
num_transformer=StandardScaler()

preprocessing=ColumnTransformer(
    [
        ('onehotencoder',oh_transformer,cat_features),
        ('standard_scaler',num_transformer,num_features)
    ]
)

In [82]:
X_train=preprocessing.fit_transform(X_train)
X_test=preprocessing.transform(X_test)

In [83]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.721708,-0.653318,0.277912,1.777611,2.053422,1.575272,0.681958,-1.273702,-0.415942,-0.058810
1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,-0.721708,-0.165525,-0.723883,-0.724971,-0.670111,-0.634811,1.409353,0.785113,-0.224146,-0.768009
2,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,-0.721708,-0.287473,1.279708,0.526320,1.508716,-0.634811,0.681958,0.785113,-0.711215,-0.768009
3,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.454995,-0.531370,0.277912,1.777611,-0.670111,-0.634811,1.409353,0.785113,0.057482,-0.058810
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,-0.721708,0.322268,-0.723883,-0.724971,-0.670111,1.575272,0.681958,0.785113,-1.139911,-0.058810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3661,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721708,-0.653318,1.279708,-0.724971,-0.670111,-0.634811,-1.500228,0.785113,-0.531928,0.650390
3662,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.454995,-0.897214,-0.723883,1.777611,-1.214818,-0.634811,1.409353,0.785113,1.528543,-0.058810
3663,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.454995,1.541750,0.277912,-0.724971,2.053422,-0.634811,-0.772833,0.785113,-0.356053,0.650390
3664,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.454995,1.785647,1.279708,-0.724971,-0.125404,-0.634811,-1.500228,0.785113,-0.248595,0.650390
3665,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721708,-0.775266,0.277912,-0.724971,-1.214818,1.575272,-0.045437,-1.273702,-1.075853,-1.477209

In [84]:
pd.DataFrame(X_test)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.454995,-0.287473,1.279708,-0.724971,-1.214818,-0.634811,-0.772833,-1.273702,-0.731873,-0.768009
1,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.366643,-0.531370,0.277912,0.526320,-1.214818,1.575272,1.409353,-1.273702,-0.664972,-0.058810
2,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.454995,0.810061,0.277912,-0.724971,0.964009,-0.634811,1.409353,0.785113,-0.416131,-0.768009
3,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,-0.721708,2.517336,2.281503,-0.724971,1.508716,-0.634811,-0.045437,0.785113,-0.109865,0.650390
4,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.454995,-1.019163,0.277912,0.526320,-0.125404,1.575272,0.681958,0.785113,-0.312653,2.068789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1217,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,-0.721708,0.200320,0.277912,1.777611,-0.125404,1.575272,-0.045437,0.785113,2.315245,0.650390
1218,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.454995,0.200320,-0.723883,-0.724971,0.419302,-0.634811,0.681958,0.785113,1.728488,-0.768009
1219,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.454995,-0.287473,0.277912,-0.724971,-1.214818,-0.634811,-0.772833,0.785113,-0.224146,-0.768009
1220,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.721708,1.541750,-1.725679,0.526320,-0.125404,-0.634811,-1.500228,0.785113,-0.535150,1.359589
1221,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721708,-0.043577,0.277912,-0.724971,-0.670111,-0.634811,0.681958,0.785113,-1.198473,-0.768009

In [91]:
#model Training
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score,recall_score,f1_score,precision_score

In [92]:
def evaluation_metrics(true,predicted):
    accuracy=accuracy_score(true,predicted)
    recall=recall_score(true,predicted)
    f1=f1_score(true,predicted)
    precision=precision_score(true,predicted)
    return accuracy,recall,f1,precision

In [93]:
models={
    'AdaBoostClassifier':AdaBoostClassifier(),
    'GradientBoostingClassifier':GradientBoostingClassifier(),
    'RandomForestClassifier':RandomForestClassifier(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    'LogisticRegression':LogisticRegression()
}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)#model training

    # Prediction
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    #Training evaluation
    accuracy_training,recall_training,f1_training,precision_training=evaluation_metrics(y_train,y_train_pred)

    #testing evaluation
    accuracy_test,recall_test,f1_test,precison_test=evaluation_metrics(y_test,y_test_pred)

    print(list(models.keys())[i])
    print('-----------training evalution----------------')
    print(f'Accuracy:{accuracy_training}')
    print(f'Recall:{recall_training}')
    print(f'F1:{f1_training}')
    print(f'precision:{precision_training}')
    print('----------------Testing evaluation-------------')
    print(f'Accuracy:{accuracy_test}')
    print(f'Recall:{recall_test}')
    print(f'F1:{f1_test}')
    print(f'precision:{precison_test}')
    print('--------------------------------------------------')

AdaBoostClassifier
-----------training evalution----------------
Accuracy:0.8390616475722859
Recall:0.2309899569583931
F1:0.3530701754385965
precision:0.7488372093023256
----------------Testing evaluation-------------
Accuracy:0.839607201309329
Recall:0.23318385650224216
F1:0.3466666666666667
precision:0.6753246753246753
--------------------------------------------------
GradientBoostingClassifier
-----------training evalution----------------
Accuracy:0.8895253682487725
Recall:0.49067431850789095
F1:0.628099173553719
precision:0.8724489795918368
----------------Testing evaluation-------------
Accuracy:0.8723404255319149
Recall:0.4125560538116592
F1:0.5411764705882353
precision:0.7863247863247863
--------------------------------------------------
RandomForestClassifier
-----------training evalution----------------
Accuracy:1.0
Recall:1.0
F1:1.0
precision:1.0
----------------Testing evaluation-------------
Accuracy:0.9279869067103109
Recall:0.6457399103139013
F1:0.7659574468085106
precision:0.9411764705882353
--------------------------------------------------
DecisionTreeClassifier
-----------training evalution----------------
Accuracy:1.0
Recall:1.0
F1:1.0
precision:1.0
----------------Testing evaluation-------------
Accuracy:0.9067103109656302
Recall:0.7713004484304933
F1:0.7510917030567685
precision:0.7319148936170212
--------------------------------------------------
LogisticRegression
-----------training evalution----------------
Accuracy:0.8431533006001091
Recall:0.2998565279770445
F1:0.4209466263846928
precision:0.706081081081081
----------------Testing evaluation-------------
Accuracy:0.8445171849427169
Recall:0.3094170403587444
F1:0.42073170731707316
precision:0.6571428571428571
--------------------------------------------------

In [94]:
rf_param={'max_depth':[5,8,10,None,15],
    'n_estimators':[100,200,300,400],
    'min_samples_split':[2,8,15,20],
    'max_features':[5,7,8,6]
}
adaboost_param={
    'n_estimators':[50,20,100,80],
    'learning_rate':[0.1,1,10,5]
}
gradient_param={
    'loss':['log_loss', 'exponential'],
    'n_estimators':[100,200,300,400],
    'criterion':['friedman_mse', 'squared_error'],
    'learning_rate':[0.1,1,10,5]
}

In [96]:
randomcv_models=[
    ('RandomForestClassifier',RandomForestClassifier(),rf_param),
    ('AdaBoostClassifier',AdaBoostClassifier(),adaboost_param),
    ('GradientBoostingClassifier',GradientBoostingClassifier(),gradient_param)
]

In [100]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import RandomizedSearchCV
model_name={}

for name,model,param in randomcv_models:
    random=RandomizedSearchCV(estimator=model,param_distributions=param,n_jobs=-1,cv=3,verbose=3,random_state=10)
    random.fit(X_train,y_train)
    model_name[name]=random.best_params_

for name in model_name:
    print(name,':',model_name[name])
    print('---------------------------------------')

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Fitting 3 folds for each of 10 candidates, totalling 30 fits
Fitting 3 folds for each of 10 candidates, totalling 30 fits
RandomForestClassifier : {'n_estimators': 300, 'min_samples_split': 2, 'max_features': 8, 'max_depth': 8}
---------------------------------------
AdaBoostClassifier : {'n_estimators': 80, 'learning_rate': 1}
---------------------------------------
GradientBoostingClassifier : {'n_estimators': 400, 'loss': 'log_loss', 'learning_rate': 0.1, 'criterion': 'friedman_mse'}
---------------------------------------

In [101]:
models={
    'AdaBoostClassifier':AdaBoostClassifier(n_estimators=80,learning_rate=1),
    'GradientBoostingClassifier':GradientBoostingClassifier(n_estimators=400,loss='log_loss',learning_rate=0.1,criterion='friedman_mse'),
    'RandomForestClassifier':RandomForestClassifier(n_estimators=300,min_samples_split=2,max_features=8,max_depth=8),
}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)#model training

    # Prediction
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    #Training evaluation
    accuracy_training,recall_training,f1_training,precision_training=evaluation_metrics(y_train,y_train_pred)

    #testing evaluation
    accuracy_test,recall_test,f1_test,precison_test=evaluation_metrics(y_test,y_test_pred)

    print(list(models.keys())[i])
    print('-----------training evalution----------------')
    print(f'Accuracy:{accuracy_training}')
    print(f'Recall:{recall_training}')
    print(f'F1:{f1_training}')
    print(f'precision:{precision_training}')
    print('----------------Testing evaluation-------------')
    print(f'Accuracy:{accuracy_test}')
    print(f'Recall:{recall_test}')
    print(f'F1:{f1_test}')
    print(f'precision:{precison_test}')
    print('--------------------------------------------------')

AdaBoostClassifier
-----------training evalution----------------
Accuracy:0.8447899618112384
Recall:0.26398852223816355
F1:0.3927427961579509
precision:0.7666666666666667
----------------Testing evaluation-------------
Accuracy:0.8436988543371522
Recall:0.24663677130044842
F1:0.3654485049833887
precision:0.7051282051282052
--------------------------------------------------
GradientBoostingClassifier
-----------training evalution----------------
Accuracy:0.9397163120567376
Recall:0.7230989956958394
F1:0.8201790073230268
precision:0.9473684210526315
----------------Testing evaluation-------------
Accuracy:0.9026186579378068
Recall:0.5650224215246636
F1:0.6792452830188679
precision:0.8513513513513513
--------------------------------------------------
RandomForestClassifier
-----------training evalution----------------
Accuracy:0.9187124931805782
Recall:0.593974175035868
F1:0.7353463587921847
precision:0.965034965034965
----------------Testing evaluation-------------
Accuracy:0.8829787234042553
Recall:0.4304932735426009
F1:0.573134328358209
precision:0.8571428571428571
--------------------------------------------------