In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [25]:
df=sns.load_dataset('tips')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [27]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [19]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [28]:
#dependent and independent features
y=df['total_bill']
X=df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [30]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cols=['sex', 'smoker', 'day', 'time']
for col in cols:
    X_train[col]=le.fit_transform(X_train[col])
    X_test[col]=le.transform(X_test[col])

In [31]:
X_train

      tip  sex  smoker  day  time  size
234  3.00    1       1  Sat     0     2
227  3.00    1       0  Sat     0     4
180  3.68    1       1  Sun     0     4
5    4.71    1       0  Sun     0     4
56   3.00    1       1  Sat     0     4
..    ...  ...     ...  ...   ...   ...
106  4.06    1       1  Sat     0     2
14   3.02    0       0  Sun     0     2
92   1.00    0       1  Fri     0     2
179  3.55    1       1  Sun     0     2
102  2.50    0       1  Sat     0     3

[170 rows x 6 columns]

In [34]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')
X_train=ct.fit_transform(X_train)
X_test=ct.transform(X_test)

In [35]:
X_train

array([[1., 0., 0., ..., 1., 0., 2.],
       [1., 0., 0., ..., 0., 0., 4.],
       [0., 1., 0., ..., 1., 0., 4.],
       ...,
       [0., 0., 0., ..., 1., 0., 2.],
       [0., 1., 0., ..., 1., 0., 2.],
       [1., 0., 0., ..., 1., 0., 3.]])

In [39]:
from sklearn.svm import SVR
svr=SVR()
svr.fit(X_train,y_train)
y_pred=svr.predict(X_test)

In [41]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=np.sqrt(mse)
score=r2_score(y_test,y_pred)
print(f'mse :{mse}')
print(f'rmse :{rmse}')
print(f'mae :{mae}')
print(f'r2_score :{score}')

mse :35.089954899771485
rmse :5.92367748107301
mae :4.175959078886017
r2_score :0.496241694353699

In [47]:
from sklearn.model_selection import GridSearchCV
param_grids={
    'C':[1,10,100,1000],
    'gamma':[1,0.1,0.01,0.001],
    'kernel':['rbf']
}

In [51]:
grid=GridSearchCV(estimator=SVR(),param_grid=param_grids,refit=True,cv=5)

In [52]:
grid.fit(X_train,y_train)
y_pred=grid.predict(X_test)

In [53]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=np.sqrt(mse)
score=r2_score(y_test,y_pred)
print(f'mse :{mse}')
print(f'rmse :{rmse}')
print(f'mae :{mae}')
print(f'r2_score :{score}')

mse :30.374578979871607
rmse :5.51131372540809
mae :3.937419108309778
r2_score :0.5639365600404485